// <auto-generated />
using System;
using Blog.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Blog.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190316202338_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Blog.Models.Article", b =>
                {
                    b.Property<int>("ArticleID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ArticleCategoryCategoryID");

                    b.Property<string>("ArticleContent")
                        .IsRequired();

                    b.Property<string>("ArticleTitle")
                        .IsRequired();

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsPrivate");

                    b.HasKey("ArticleID");

                    b.HasIndex("ArticleCategoryCategoryID");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Blog.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryName")
                        .IsRequired();

                    b.Property<int?>("FatherCategoryCategoryID");

                    b.Property<bool>("IsDeleted");

                    b.HasKey("CategoryID");

                    b.HasIndex("FatherCategoryCategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Blog.Models.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CommentArticleArticleID");

                    b.Property<string>("CommentContent")
                        .IsRequired();

                    b.Property<int>("CommentUserUserID");

                    b.Property<bool>("IsDeleted");

                    b.HasKey("CommentID");

                    b.HasIndex("CommentArticleArticleID");

                    b.HasIndex("CommentUserUserID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Blog.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<int>("UserRole");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("UserID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Blog.Models.Article", b =>
                {
                    b.HasOne("Blog.Models.Category", "ArticleCategory")
                        .WithMany()
                        .HasForeignKey("ArticleCategoryCategoryID");
                });

            modelBuilder.Entity("Blog.Models.Category", b =>
                {
                    b.HasOne("Blog.Models.Category", "FatherCategory")
                        .WithMany()
                        .HasForeignKey("FatherCategoryCategoryID");
                });

            modelBuilder.Entity("Blog.Models.Comment", b =>
                {
                    b.HasOne("Blog.Models.Article", "CommentArticle")
                        .WithMany()
                        .HasForeignKey("CommentArticleArticleID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Blog.Models.User", "CommentUser")
                        .WithMany()
                        .HasForeignKey("CommentUserUserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
